name: Release
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - run: sbt ci-release
        env:
          # define Java options for both official sbt and sbt-extras
          JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
          JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          CI_RELEASE: publishSigned
      - name: Release
        run: |
          sudo apt-get update
          sudo apt install clang libunwind-dev libgc-dev libre2-dev
          sbt -v ci-release
          env SCALAJS_VERSION="0.6.33" CI_RELEASE="clean;expectyJS2_11/publishSigned;expectyJS2_12/publishSigned;expectyJS/publishSigned" sbt -v ci-release
          env SCALANATIVE_VERSION="0.4.0-M2" CI_RELEASE="clean;expectyNative2_11/publishSigned" sbt -v ci-release
        shell: bash
